export const ControlsActionTypes = {
    TOGGLE_GRAPH: 'TOGGLE_GRAPH',
    TOGGLE_NOTIFICATIONS: 'TOGGLE_NOTIFICATIONS',
    SET_NOTIFICATION: 'SET_NOTIFICATION',
    CHANGE_GRAPH_FILTER: 'CHANGE_GRAPH_FILTER'
}