export const ChatActionTypes = {
    ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE',
    SET_MESSAGES: 'SET_MESSAGES',
    FETCH_MESSAGES: 'FETCH_MESSAGES',
    FETCH_PATTERNS: 'FETCH_PATTERNS',
    SET_METADATA: 'SET_METADATA',
    SET_PATTERNS: 'SET_PATTERNS',
    CLEAR_MESSAGES: 'CLEAR_MESSAGES',
    CLEAR_HISTORY: 'CLEAR_HISTORY',
    ADD_NEW_HISTORY_ITEM: 'ADD_NEW_HISTORY_ITEM'
}